//authAction
export const AUTH_RESULT = "AUTH_RESULT";
export const REG_RESULT = "REG_RESULT";
export const SET_FORM_DATA = {
    USERNAME_SET : "USERNAME_SET",
    EMAIL_SET: "EMAIL_SET",
    PASSWORD_SET: "PASSWORD_SET",
};
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CURE_RESULT = "CURE_RESULT";

//productAction
export const GET_WHOLE_PRODUCTS = "GET_WHOLE_PRODUCTS";
export const GET_CURRENT_PRODUCT = "GET_CURRENT_PRODUCT";
export const SET_PRODUCT_DATA = {
    PRODNAME_SET : 'PRODNAME_SET',
    CALORIES_SET : 'CALORIES_SET',
    FAT_SET : 'FAT_SET',
    CARBS_SET : 'CARBS_SET',
    PROTEIN_SET : 'PROTEIN_SET',
};
export const ADD_SUCCESS = "ADD_SUCCESS";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const REMOVE_SUCCESS = "REMOVE_SUCCESS";